import React from 'react';
import ReactDOM from 'react-dom';

// import Button from './component/Button.js';
// import Flex from './component/Flex.js';
// import Drawer from './component/Drawer.js';
// import Menu from './component/Menu.js';
// import NavBar from './component/NavBar.js';
// import Popover from './component/Popover.js';
// import Pagination from './component/Pagination.js';
// import SegmentedControl from './component/SegmentedControl.js';
// import Tab from './component/Tab.js';
// import TabBar from './component/TabBar.js';
// import Calendar from './component/Calendar.js';
// import DatePicker from './component/DatePicker.js';
// import DatePickerView from './component/DatePickerView.js';
// import ImgPicker from './component/InputItem.js';
// import InputItem from './component/InputItem.js';
// import Range from './component/range.js';
// import Radio from './component/Radio.js';
// import Switch from './component/Switch.js';
// import Search from './component/Search.js';
// import Slider from './component/Slider.js';
// import Stepper from './component/Stepper.js';
// import Textarea from './component/Textarea.js';
// import Accordion from './component/Accordion.js';
// import Badge from './component/Badge.js';
// import Carousel from './component/Carousel.js';
// import Card from './component/Card.js';
// import Grid from './component/Grid.js';
// import Icon from './component/Icon.js';
// import List from './component/List.js';
// import NoticeBar from './component/NoticeBar.js';
// import Steps from './component/Steps.js';
// import Tag from './component/Tag.js';
// import ActionSheet from './component/ActionSheet.js';
// import ActivityIndicator from './component/ActivityIndicator.js';
// import Modal from './component/Modal.js';
// import Progress from './component/Progress.js';
// import Toast from './component/Toast.js';
// import PullToRefresh from './component/PullToRefresh.js';
// import SwipeAction from './component/SwipeAction.js';
import ListView from './component/ListView.js';
// import Result from './component/Result.js';
// import LocalProvider from './component/LocalProvider.js';

ReactDOM.render(<ListView  />, document.getElementById('root'));
